### ISSUE TITLE
bash: ./Tidal-DL_Lin_x86: No such file or directory

### ISSUE THREAD

**Issue by ryanphobia** [Sorrow446/Ti-DL#1]
when i was set permission with chmod +x Tidal-DL_Lin_x86
I can't run this app with error like in the screenshot, in case i use lubuntu 18.04 x64

![2019-03-06-130450_1366x768_scrot](https://user-images.githubusercontent.com/31889853/53859837-95998a00-4011-11e9-9e6b-cff6877a9844.png)

**Comment by Sorrow446** [comment]
Unfortunately, you can't run x86 executables on x64 versions of Linux like you can with Windows. Reason why there's no x64 Linux ver yet is because I need to set up my VM again.

**Comment by ryanphobia** [comment]
oh, ok I hope you'll be release for linux x64 version

**Comment by Sorrow446** [comment]
x64 build out now :).
