### ISSUE TITLE
can't batch download with option list

### ISSUE THREAD

**Issue by ryanphobia** [Sorrow446/Ti-DL#4]
I use option ./Ti-DL_Lin_x64 -list list.txt and will come error "Traceback (most recent call last):
  File "/home/user/Desktop/Tidal-DL_Lin.py", line 371, in <module>
NameError: name 'istrack' is not defined
[29956] Failed to execute script Tidal-DL_Lin" like on this screenshot below

![Screenshot_20190314_220019](https://user-images.githubusercontent.com/31889853/54367397-e01ba600-46a4-11e9-8f74-134cc3aab037.png)

**Comment by Sorrow446** [comment]
Thought I fixed this, sorry. Will fix tomorrow if I have time.

**Comment by Sorrow446** [comment]
Try [this test build](https://thoas.feralhosting.com/sorrow/Tidal-DL/Ti-DL_R1e_testbuildlin.zip). I need to do further testing before releasing to the page.

**Comment by ryanphobia** [comment]
ok, I will try it

**Comment by ryanphobia** [comment]
ok, thank you very much, the test build is work well using -list command
